{{- if and .Values.logrotate.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{- if .Values.logrotate.rbac.serviceAccount.name }}
  name: {{ .Values.logrotate.rbac.serviceAccount.name }}
{{- else }}
  name: {{ template "logrotate.name" . }}
{{- end }}
{{- end }}