logrotate:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 1.0.0
  namespace: logrotate

  # securityContext:
  #   privileged: true   

  image:
    name: lucasafonsokremer/kubernetes-logrotate:tagname
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  rbac:
    create: false
    serviceAccount:
      name: ""

  environment:
    cronSchedule: */5 * * * *

  tolerations: {}
  # - effect: NoSchedule
  #   operator: Exists

  config:
    k8sRotatorConf: |-
      /var/lib/docker/volumes/*/*.log {
        rotate 1
        copytruncate
        missingok
        notifempty
        compress
        maxsize 100M
        daily
        create 1234 dummy dummy
        dateext
        dateformat -logrotate-%Y-%m-%d-%H-%M
      }
